
# Database Config
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = postgres
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/quotationdb
quarkus.hibernate-orm.schema-management.strategy = update

# Kafka Config
mp.messaging.outgoing.quotation-channel.connector = smallrye-kafka
mp.messaging.outgoing.quotation-channel.topic = quotation
mp.messaging.connector.smallrye-kafka.bootstrap.servers = localhost:9092

quarkus.rest-client."org.lispy.mineracao.client.CurrencyPriceClient".url=https://economia.awesomeapi.com.br